"""empty message

Revision ID: 75d7d36f3f6f
Revises: 58e0a2b049ce
Create Date: 2021-04-26 12:30:15.868102

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75d7d36f3f6f'
down_revision = '58e0a2b049ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Adjusted nullable=False to True to allow us to add the column via the db upgrade path
    op.add_column('todos', sa.Column('completed', sa.Boolean(), nullable=True))

    # Alembic allows us to pass in a SQL command that will lets us set the completed column value to False
    op.execute('UPDATE todos SET completed = False WHERE completed IS NULL;')

    # Now reset the constraint of the column back to False
    op.alter_column('todos', 'completed', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todos', 'completed')
    # ### end Alembic commands ###
